### ISSUE TITLE
unknown data

### ISSUE THREAD

**Issue by wiredots01** [amoilanen/sniffr#4]
<img width="252" alt="screen shot 2016-10-25 at 4 19 09 pm" src="https://cloud.githubusercontent.com/assets/4254904/19678062/c6f0914c-9ace-11e6-95e5-0ac6ba41f355.png">

im using google chrome

**Comment by antivanov** [comment]
Hi, thanks for filing this issue.

Can you, please, provide the user agent string from the version of Google Chrome used? 
What does the following print in the browser console?

```javascript
console.log(navigator.userAgent);
```

**Comment by Filliposniper** [comment]
Am also having the same issue.. all I see is unknown.

**Comment by antivanov** [comment]
@Filliposniper Can you, please post the value of `navigator.userAgent` executed in the browser console? Which browser/OS is this problem reproducible with?

**Comment by amoilanen** [comment]
Closing the issue since no specific user agent strings were provided/inactivity. Will try to update the library with the most recent user agent strings
